# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    RemiBundle\:
        resource: '../../src/RemiBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/RemiBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    RemiBundle\Controller\:
        resource: '../../src/RemiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    remi.file_uploader.drapeaux:
        class: RemiBundle\Services\FileUploader
        arguments:
            $targetDir: '%drapeaux_directory%'
        public: true

    remi.file_uploader.photos:
        class: RemiBundle\Services\FileUploader
        arguments:
            $targetDir: '%photos_directory%'
        public: true

    RemiBundle\Listener\DrapeauUploaderListener:
        arguments:
            $uploader: '@remi.file_uploader.drapeaux'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    RemiBundle\Listener\PhotoUploaderListener:
        arguments:
            $uploader: '@remi.file_uploader.photos'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    remi.ville_handler:
        class: RemiBundle\Services\VilleHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@serializer'
        public: true